#!/usr/bin/env bash
#
# Add a device that cannot run new-peer.sh on itself - a Windows box,
# a phone - to the tunnel.
#
#   new-peer-local.sh <inventory-host> <name> <tunnel-ipv4> <tunnel-ipv6>
#
# e.g.
#
#   roles/wireguard/scripts/new-peer-local.sh \
#     carcosa Chtugha 10.7.0.2 fd9c:a40e:a2a8::2
#
# The one difference from new-peer.sh is where the device's private
# key is born: there on the device, here on the controller. What comes
# out is the device's whole configuration, written to
# roles/wireguard/keys/<name>.conf - which is gitignored, like
# roles/sshd/keys/ and roles/nsd/keys/ before it. Carry it to the
# device, and it stays here and nowhere else. The repository keeps
# only the public key and the preshared key, in the inventory, neither
# of which decrypts anything on its own.
#
# Prefer new-peer.sh wherever the device can run it: a key that never
# travels is a stronger position than a key that travels once.
#
# Note the consequence of not storing these: a configuration lost with
# the device cannot be reissued from here. Re-key that peer instead -
# run this again for it and replace its inventory entry.
#
# Everything else - the endpoint, the resolvers, the MTU, the server's
# public key - is read from the inventory for <inventory-host>, so a
# peer's configuration cannot drift from the tunnel it joins. The
# server's private key is read only to derive its public half, and is
# never printed.
#
# Run from the repository root: ansible.cfg is what points ansible at
# the vault password.
set -euo pipefail

if [ "$#" -ne 4 ]; then
  sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//' >&2
  exit 1
fi

host="$1"
name="$2"
ip4="$3"
ip6="$4"

[ -f ansible.cfg ] || {
  echo "Run this from the repository root." >&2
  exit 1
}
for tool in wg ansible python3; do
  command -v "${tool}" >/dev/null || {
    echo "${tool} not found. Run this from the Dev Container." >&2
    exit 1
  }
done

out="roles/wireguard/keys/${name}.conf"
[ -e "${out}" ] && {
  echo "${out} exists. Delete it first to re-key ${name}." >&2
  exit 1
}

# Everything the peer needs from the inventory, in one templated
# read. `ansible-inventory` is not enough: it prints the variables
# unresolved, so `wireguard.server.private_key` comes back as the
# literal `{{ wireguard_server_private_key }}`.
#
# ANSIBLE_LOG_PATH matters as much as the command does. ansible.cfg
# points log_path at log/ansible.log, and an ad-hoc `debug` writes its
# whole result there - which for this call would mean the server's
# private key in plaintext, in a file, indefinitely.
settings="$(
  ANSIBLE_LOG_PATH=/dev/null ansible -i inventories/machines.yml "${host}" \
    -m ansible.builtin.debug \
    -a "msg={{ {'domain': domain, 'wg': wireguard} | to_json }}"
)"

# One key of that result, dotted. Lists come back joined, which is the
# form both `DNS =` and `Address =` want.
get() {
  printf '%s' "${settings}" | python3 -c '
import json
import sys

# `host | SUCCESS => {json}` - cut the banner at the first brace,
# then unwrap the JSON string `debug` wrapped the value in.
result = sys.stdin.read()
value = json.loads(json.loads(result[result.index("{"):])["msg"])
for key in sys.argv[1].split("."):
  value = value[key]
print(", ".join(value) if isinstance(value, list) else value)
' "$1"
}

# The public half is what peers need; the private half stays in the
# pipe and is never assigned to a variable.
server_public="$(get wg.server.private_key | wg pubkey)"
endpoint="vpn.$(get domain)"
listen_port="$(get wg.listen_port)"
redirect_port="$(get wg.redirect_port)"

private="$(wg genkey)"
public="$(printf '%s' "${private}" | wg pubkey)"
preshared="$(wg genpsk)"

mkdir -p "$(dirname "${out}")"
chmod 0700 "$(dirname "${out}")"
# Created before it is written to, so the private key is never
# readable by anyone else, not even for the moment between the two.
touch "${out}"
chmod 0600 "${out}"
cat > "${out}" <<CONF
# ${name}, on the ${endpoint} tunnel. Generated by
# roles/wireguard/scripts/new-peer-local.sh; the matching [Peer] entry
# is in inventories/group_vars/*/wireguard.yml.
[Interface]
PrivateKey = ${private}
Address = ${ip4}/32, ${ip6}/128
# The resolver on the far end of the tunnel. With a full tunnel this
# matters: without it the device keeps using the local network's
# resolver, which then sees every name looked up.
DNS = $(get wg.dns)
MTU = $(get wg.mtu)

[Peer]
PublicKey = ${server_public}
PresharedKey = ${preshared}
# Everything, both families. The device's own LAN keeps working: its
# on-link route is more specific, on Linux through wg-quick's policy
# routing and on Windows through the interface metric.
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = ${endpoint}:${listen_port}
# On a network that permits nothing but 443 outbound, use this line
# instead - the firewall redirects it to ${listen_port} before the filter
# table sees the packet. It defeats a port filter, not a protocol one.
#Endpoint = ${endpoint}:${redirect_port}
# Hole-punching is not needed - the server has a public address - but
# a keepalive stops a mobile carrier's NAT dropping the mapping while
# the device is idle, which is what makes an incoming connection from
# another peer work.
PersistentKeepalive = 25
CONF
echo "wrote ${out} - carry it to ${name}, it is not stored anywhere else" >&2

cat <<YAML

# ---------- for wireguard_peers in the inventory ----------
  - name: ${name}
    public_key: ${public}
    ip4: ${ip4}
    ip6: ${ip6}
YAML
# encrypt_string indents the block scalar to line up under its own
# key. Re-indent to the repo's 2-space style, nested one level deeper
# than the `- name:` above.
ansible-vault encrypt_string "${preshared}" --name preshared_key \
  | sed -e '1s/^/    /' -e '1!s/^ */      /'

# Not a strong guarantee - both values have already been through a
# pipe - but free.
unset private public preshared
